import koa from 'koa'
import Router from 'koa-router'
import bodyParser from 'koa-bodyparser'
import { registerRoutrs } from './routes/registerRoutes'
import swaggerUi from 'swagger-ui-koa'
import * as swaggerDocument from './swagger.json'

const app = new koa()
const router = new Router()

const app = new Koa<AppBookDatabaseState & AppWarehouseDatabaseState,
Koa.DefaultContext>()
app.use(async (ctx, next): Promise<void> => {
ctx.state = state
await next()
})

app.use(swaggerUi.serve)
app.use (swaggerUi.setup(swaggerDocument))

app.use(bodyParser())
registerRoutes(router)
app.use(router.routes()).use(router.allowedMethods())

app.use(koaSwagger({
    routePrefix: '/docs',
    specPrefix: '/docs/spec',
    exposeSpec: true,
    swaggerOptions: {
        spec: swagger // This object is an import of the swagger.json generated by tsoa
    }
    }
}))

export default app